### ISSUE TITLE
 Nextjs - Build error occurred - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by alaaomri** [CommandersAct/react-tag-commander#26]
I'm integrating react-tag-commander in Nextjs project, but when I'm trying to build my solution I  found some issues 

> Build error occurred
C:\XXXXXXXXXXXXXXXXXXXXX\node_modules\react-tag-commander\src\index.js:1
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe 

- [ ] 

- [ ] (internal/modules/cjs/loader.js:1001:16)

    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)

**Comment by jeandesravines** [comment]
Hello,

I don’t know if you resolved your issue but you have to import the es5 variant: 
`import TagCommander from “react-tag-commander/dist/index.es5.min`

(CommandersAct should update their package.json to change the `main` attribute)

Have a great day,

Jean

**Comment by thepiwo** [comment]
I will close this for now, feel free to reopen if the issue persists
